Fix SVG detection for files missing XML declaration
bolt/filesystem pull request #46
Opened 2017-03-24 23:51 UTC by CarsonF

Fixes https://github.com/bolt/bolt/issues/6487

2017-03-25 07:52 UTC, GawainLynch commented
Test(s) good … Real use, bad:
![screenshot from 2017-03-25 08-51-36](https://cloud.githubusercontent.com/assets/1427081/24320578/4e55854a-1138-11e7-8c5b-5c395eb96ec6.png)

2017-03-25 07:53 UTC, GwendolenLynch requested changes

2017-03-25 07:53 UTC, GawainLynch commented on tests/Handler/Image/InfoTest.php
> +        $data = substr($data, 39);
For a 2 KiB file, aren't we better off adding a second cut-down version?

2017-03-25 15:00 UTC, CarsonF commented on tests/Handler/Image/InfoTest.php
> +        $data = substr($data, 39);
I was trying not to add another file, because it throws off all the finder / iterator tests which list all the files.

2017-03-25 15:03 UTC, GawainLynch commented on tests/Handler/Image/InfoTest.php
> +        $data = substr($data, 39);
Grumble grumble … OK then :laughing:

2017-03-25 15:03 UTC, GwendolenLynch approved these changes

2017-03-25 15:07 UTC, CarsonF commented
Everything seems to work fine for me, I can't reproduce your errors. Maybe your setup was bad?

2017-03-25 15:28 UTC, GawainLynch commented
![screenshot from 2017-03-25 16-26-13](https://cloud.githubusercontent.com/assets/1427081/24323560/ccafc218-1177-11e7-9977-601bea16bc6a.png)
`only_aliases: false`

2017-03-25 15:38 UTC, CarsonF commented
Ah, yeah. I was wondering if that would need to be handled. `Filesystem::getMimeType` still returns the non-corrected value. Unfortunately, that's not going to be as easy to fix since that functionality is delegated to the adapters. 

Maybe we can change the check in thumbs.

2017-03-25 15:45 UTC, CarsonF commented
So thumbs currently does
```php
$image->getMimeType()
```
which goes straight to the adapter.

We could change it to
```php
$image->getInfo()->getType()->getMimeType()
```
which obviously goes through our logic to get the correct mime type. 

However, that kinda leaves `Filesystem::getMimeType` out in the cold since it doesn't always work for SVGs. Not sure the best way forward

2017-03-27 15:06 UTC, CarsonF commented
@GawainLynch Had an idea, see if latest commit works for you.

2017-03-27 15:20 UTC, GawainLynch commented
WFM :+1:

2017-03-27 15:23 UTC, merged