Use loose SemVer constraint on miljar/php-exif
bolt/filesystem pull request #61
Opened 2017-08-02 05:21 UTC by GawainLynch

The `miljar/php-exif` repository doesn't use strict SemVer, but we're locked onto 0.5.x. 

c.f. [code changes](https://github.com/PHPExif/php-exif/compare/v0.5.1...v0.6.3)

2017-08-02 19:21 UTC, CarsonF requested changes
We need to update to `^0.6` instead.

Right now we are expecting that `RuntimeException` which they replaced with a `return false`.

2017-08-03 10:12 UTC, GawainLynch commented
Also added a reflection test against `Image\Info::readExif()` … Don't even think of asking me to mock the native function in `createFromFile()` :wink:

2017-08-03 10:20 UTC, GawainLynch commented
Oh, and for reference I missed the `.z` in the upstream README, hence my assertion about their use of SemVer … 
![only human](https://user-images.githubusercontent.com/1427081/28917469-10d32c16-7846-11e7-947e-528e08d29dc6.jpg)

2017-08-03 17:50 UTC, CarsonF approved these changes

2017-08-03 18:34 UTC, merged